export const SENT_REQUEST_TO_SERVER = 'SENT_REQUEST_TO_SERVER'
export const RECEIVED_RESPONSE_FROM_SERVER = 'RECEIVED_RESPONSE_FROM_SERVER'

export const FINISH_INITIAL_LOADING = 'FINISH_INITIAL_LOADING'

export const SET_TOP_MESSAGE = 'SET_TOP_MESSAGE'
