export const FETCH_RECORD = 'FETCH_RECORD'
export const RECEIVED_RECORD = 'RECEIVED_RECORD'

export const FETCH_RECORDS = 'FETCH_RECORDS'
export const RECEIVED_RECORDS = 'RECEIVED_RECORDS'

export const FETCH_ATTACHMENT = 'FETCH_ATTACHMENT'
export const RECEIVED_ATTACHMENT = 'RECEIVED_ATTACHMENT'

export const REQUEST_CREATE_RECORD = 'REQUEST_CREATE_RECORD'
export const RECEIVED_RECORD_CREATE_ACK = 'RECEIVED_RECORD_CREATE_ACK'

export const REQUEST_UPDATE_RECORD = 'REQUEST_UPDATE_RECORD'
export const RECEIVED_UPDATE_RECORD_ACK = 'RECEIVED_UPDATE_RECORD_ACK'

export const REQUEST_DELETE_RECORD = 'REQUEST_DELETE_RECORD'
export const RECEIVED_RECORD_DELETE_ACK = 'RECEIVED_RECORD_DELETE_ACK'
