export const FETCH_PROFILE = 'FETCH_PROFILE'
export const RECEIVED_PROFILE = 'RECEIVED_PROFILE'

export const FETCH_EXTERNAL_PROFILES = 'FETCH_EXTERNAL_PROFILES'
export const RECEIVED_EXTERNAL_PROFILES = 'RECEIVED_EXTERNAL_PROFILES'

export const FETCH_ALIASES = 'FETCH_ALIASES'
export const RECEIVED_ALIASES = 'RECEIVED_ALIASES'

export const FETCH_SETTINGS = 'FETCH_SETTINGS'
export const RECEIVED_SETTINGS = 'RECEIVED_SETTINGS'

export const FETCH_EMAILS = 'FETCH_EMAILS'
export const RECEIVED_EMAILS = 'RECEIVED_EMAILS'
