export const FETCH_RESEARCHER = 'FETCH_RESEARCHER'
export const RECEIVED_RESEARCHER = 'RECEIVED_RESEARCHER'

export const FETCH_RESEARCHERS = 'FETCH_RESEARCHERS'
export const RECEIVED_RESEARCHERS = 'RECEIVED_RESEARCHERS'

export const FETCH_RECORDS = 'FETCH_RECORDS'
export const RECEIVED_RECORDS = 'RECEIVED_RECORDS'

export const FETCH_AFFILIATIONS = 'FETCH_AFFILIATIONS'
export const RECEIVED_AFFILIATIONS = 'RECEIVED_AFFILIATIONS'

export const FETCH_COAUTHORS = 'FETCH_COAUTHORS'
export const RECEIVED_COAUTHORS = 'RECEIVED_COAUTHORS'

export const FETCH_FUNDINGS = 'FETCH_FUNDINGS'
export const RECEIVED_FUNDINGS = 'RECEIVED_FUNDINGS'

export const FETCH_SUPERVISIONS = 'FETCH_SUPERVISIONS'
export const RECEIVED_SUPERVISIONS = 'RECEIVED_SUPERVISIONS'

export const FETCH_BIO = 'FETCH_BIO'
export const RECEIVED_BIO = 'RECEIVED_BIO'
