export const UPDATE_CAN_CLICK_NEXT = 'UPDATE_CAN_CLICK_NEXT'

export const UPDATE_NAME = 'UPDATE_NAME'
export const UPDATE_EMAIL = 'UPDATE_EMAIL'
export const UPDATE_USERNAME = 'UPDATE_USERNAME'

export const UPDATE_AFFILIATIONS = 'UPDATE_AFFILIATIONS'
export const UPDATE_ALIASES = 'UPDATE_ALIASES'
