export const FETCH_UNIT = 'FETCH_UNIT'
export const RECEIVED_UNIT = 'RECEIVED_UNIT'

export const FETCH_UNITS = 'FETCH_UNITS'
export const RECEIVED_UNITS = 'RECEIVED_UNITS'

export const FETCH_UNIT_TYPES = 'FETCH_UNIT_TYPES'
export const RECEIVED_UNIT_TYPES = 'RECEIVED_UNIT_TYPES'

export const FETCH_RECORDS = 'FETCH_RECORDS'
export const RECEIVED_RECORDS = 'RECEIVED_RECORDS'

export const FETCH_MEMBERS = 'FETCH_MEMBERS'
export const RECEIVED_MEMBERS = 'RECEIVED_MEMBERS'

export const FETCH_MANAGERS = 'FETCH_MANAGERS'
export const RECEIVED_MANAGERS = 'RECEIVED_MANAGERS'

export const FETCH_SUBUNITS = 'FETCH_SUBUNITS'
export const RECEIVED_SUBUNITS = 'RECEIVED_SUBUNITS'

export const REQUEST_CREATE_UNIT = 'REQUEST_CREATE_UNIT'
export const RECEIVED_UNIT_CREATE_ACK = 'RECEIVED_UNIT_CREATE_ACK'

export const REQUEST_UPDATE_UNIT = 'REQUEST_UPDATE_UNIT'
export const RECEIVED_UPDATE_UNIT_ACK = 'RECEIVED_UPDATE_UNIT_ACK'

export const REQUEST_DELETE_UNIT = 'REQUEST_DELETE_UNIT'
export const RECEIVED_UNIT_DELETE_ACK = 'RECEIVED_UNIT_DELETE_ACK'

export const REQUEST_CREATE_UNIT_MEMBER = 'REQUEST_CREATE_UNIT_MEMBER'
export const RECEIVED_UNIT_MEMBER_CREATE_ACK = 'RECEIVED_UNIT_MEMBER_CREATE_ACK'

export const REQUEST_UPDATE_UNIT_MEMBER = 'REQUEST_UPDATE_UNIT_MEMBER'
export const RECEIVED_UPDATE_MEMBER_UNIT_ACK = 'RECEIVED_UPDATE_MEMBER_UNIT_ACK'

export const REQUEST_DELETE_UNIT_MEMBER = 'REQUEST_DELETE_UNIT_MEMBER'
export const RECEIVED_UNIT_MEMBER_DELETE_ACK = 'RECEIVED_UNIT_MEMBER_DELETE_ACK'
